language: php

php:
    - '7.0'

install:
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpcs --standard=psr2 src tests
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/php-coveralls
